<a href="https://colab.research.google.com/github/muthuram1980/muthuramg/blob/master/BMS_NumPy_in_Python_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy Library in Python - 01**


**NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.**

**It is the fundamental package for scientific computing with Python**

**It contains various features including these important ones:**

**a) A powerful N-dimensional array object**

**b) Sophisticated (broadcasting) functions**

**c) Tools for integrating C/C++ and Fortran code**

**d) Useful linear algebra, Fourier transform, and random number capabilities**

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.

Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.



# **1) Arrays in NumPy**

**NumPy’s main object is the homogeneous multidimensional array.**

**It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.**

**In NumPy dimensions are called  axes. The number of axes is rank.**

**NumPy’s array class is called ndarray. It is also known by the alias array.**

In [0]:
import numpy as np 
  
A = np.array([1, 2, 3]) 

print(A)

print("\nType of A: ", type(A)) 
  
print("\nDimension of A: ", A.ndim) 
  
print("\nShape of A: ", A.shape) 

print("\nSize of A: ", A.size)

print("\nElements Type of A: ", A.dtype)
  
print("\nRank of A: ", np.linalg.matrix_rank(A)) 
  
#print("\nTrace of A: ", np.trace(A)) 
  


[1 2 3]

Type of A:  <class 'numpy.ndarray'>

Dimension of A:  1

Shape of A:  (3,)

Size of A:  3

Elements Type of A:  int64

Rank of A:  1


In [0]:
import numpy as np 
  
B = np.array([[1, 2, 3], 
              [4, 2, 6], 
              [7, 5, 9]]) 

print(B)

print()

print("\nType of B: ", type(B)) 
  
print("\nDimension of B: ", B.ndim) 
  
print("\nShape of B: ", B.shape) 

print("\nSize of B: ", B.size)

print("\nElements Type of B: ", B.dtype)
  
print("\nRank of B: ", np.linalg.matrix_rank(B)) 
  
print("\nTrace of B: ", np.trace(B)) 
  


[[1 2 3]
 [4 2 6]
 [7 5 9]]


Type of B:  <class 'numpy.ndarray'>

Dimension of B:  2

Shape of B:  (3, 3)

Size of B:  9

Elements Type of B:  int64

Rank of B:  3

Trace of B:  12


In [0]:
A = np.array([1, 2, 3]) 
B = np.array([[1, 2, 3], 
              [4, 2, 6], 
              [7, 5, 9]]) 
C = np.array([[[1, 2, 3], 
              [2, 4, 6], 
              [7, 5, 9]]]) 
D = np.array([[[1, 2, 3], 
              [2, 4, 6], 
              [4, 8, 12]]]) 
print("\n Array A :\n", A)
print("\nRank of A: ", np.linalg.matrix_rank(A)) 
print("\n Array B :\n", B)
print("\nRank of B: ", np.linalg.matrix_rank(B)) 
print("\n Array C :\n", C)
print("\nRank of C: ", np.linalg.matrix_rank(C)) 
print("\n Array D :\n", D)
print("\nRank of D: ", np.linalg.matrix_rank(D)) 



 Array A :
 [1 2 3]

Rank of A:  1

 Array B :
 [[1 2 3]
 [4 2 6]
 [7 5 9]]

Rank of B:  3

 Array C :
 [[[1 2 3]
  [2 4 6]
  [7 5 9]]]

Rank of C:  [2]

 Array D :
 [[[ 1  2  3]
  [ 2  4  6]
  [ 4  8 12]]]

Rank of D:  [1]


# **2) Arrays Creation**

**There are various ways to create arrays in NumPy.**

**a) For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.**

**b) Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.**

**For example: np.zeros, np.ones, np.full, np.empty, etc.**

**c) To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.**

  **i) arange: returns evenly spaced values within a given interval. step size is specified**

   **ii) linspace: returns evenly spaced values within a given interval. num no. of elements are returned.**

**d) Reshaping array: We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is: a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)**

**e) Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.**

**Note: Type of array can be explicitly defined while creating array.**

In [0]:
# Python program to demonstrate 
# array creation techniques 
import numpy as np 
  
# Creating array from the Python list 
a = np.array([1, 2, 4])
print ("Array created using passed list:\n", a) 
  
# Creating array from tuple 
b = np.array((1, 3, 2)) 
print ("\nArray created using passed tuple:\n", b) 
  
# Creating a 3X3 array with all zeros 
c = np.zeros((3, 3)) 
print ("\nAn array initialized with all zeros:\n", c) 

# Creating a 3X3 array with all ones 
c = np.ones((3, 3)) 
print ("\nAn array initialized with all ones:\n", c)

# Creating a 3X3 array with all 7s 
d = np.full((3, 3), 7) 
print ("\nAn array initialized with all 7s:\n",d)
  
# Create a constant value array of float type 
d = np.full((3, 3), 7, dtype = 'float') 
print ("\nAn array initialized with all 7s. Array type is float:\n", d) 

# Create a constant value array of complex type 
e = np.full((3, 3), 6, dtype = 'complex') 
print ("\nAn array initialized with all 6s. Array type is complex:\n", e) 

# Create an array with random values 
f = np.random.random((2, 2)) 
print ("\nA random array:\n", f) 
  
# Create a sequence of integers  
# from 0 to 30 with steps of 5 
g = np.arange(0, 30, 5) 
print ("\nA sequential array with steps of 5:\n", g) 
  
# Create a sequence of 10 values in range 0 to 5 
h = np.linspace(0, 5, 10) 
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", h) 
  


Array created using passed list:
 [1 2 4]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

An array initialized with all ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

An array initialized with all 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

An array initialized with all 7s. Array type is float:
 [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]

An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.53651767 0.96016945]
 [0.55591698 0.99448555]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [0]:
# Creating a 2x2 array with empty values 
i = np.empty([2, 2]) 
print ("\nAn array initialized with all empty values:\n", i)



An array initialized with all empty values:
 [[0.53651767 0.96016945]
 [0.55591698 0.99448555]]


### The np.empty() function is used to create a 2D array filled with all zeros. 

### Often the array is filled with values near zero because of the way memory and RAM works in the computer.

In [0]:
# Creation of arrays of different dimensions using random method 

np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 3))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 3, 3))  # Three-dimensional array
print ("\nOne dimensional array:\n", x1)
print ("\nTwo dimensional array:\n", x2)
print ("\nThree dimensional array:\n", x3)



One dimensional array:
 [5 0 3 3 7 9]

Two dimensional array:
 [[3 5 2]
 [4 7 6]
 [8 8 1]]

Three dimensional array:
 [[[6 7 7]
  [8 1 5]
  [9 8 9]]

 [[4 3 0]
  [3 5 0]
  [2 3 8]]

 [[1 3 3]
  [3 7 0]
  [1 9 9]]]


# **3) Array Indexing**

**Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing.**

**Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.**

**Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.**

**Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.**

## **a) Indexing related Operations in One Dimensional Array**

In [0]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [0]:
x1[0]

5

In [0]:
x1[4]

7

In [0]:
x1[-1]

9

In [0]:
x1[-2]

7

In [0]:
x1[0]=8
x1

array([8, 0, 3, 3, 7, 9])

In [0]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## **b) Indexing related Operations in Two Dimensional Array**

In [0]:
np.random.seed(0)  # seed for reproducibility
x2 = np.random.randint(10, size=(3, 3))  # Two-dimensional array
x2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [0]:
x2[0,0]

5

In [0]:
x2[2,1]

5

In [0]:
x2[2,-1]

2

In [0]:
x2[0, 0] = 12
x2

array([[12,  0,  3],
       [ 3,  7,  9],
       [ 3,  5,  2]])

In [0]:
# Integer array indexing example 
temp = x2[[0, 1, 2, 1], [2, 2, 1, 0]] 

print ("\nElements at indices (0, 2), (1, 2), (2, 1),"
                                    "(1, 0):\n", temp) 


Elements at indices (0, 2), (1, 2), (2, 1),(1, 0):
 [3 9 5 3]


In [0]:
# boolean array indexing example 
cond = x2 > 0 # cond is a boolean array 
temp = x2[cond] 
print ("\nElements greater than 0:\n", temp) 


Elements greater than 0:
 [12  3  3  7  9  3  5  2]


## **c) Indexing related Operations in Three Dimensional Array**

In [0]:
np.random.seed(0)  # seed for reproducibility
x3 = np.random.randint(10, size=(3, 3, 3))  # Three-dimensional array
x3

array([[[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]],

       [[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]],

       [[8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]]])

In [0]:
x3[0,0,0]

5

In [0]:
x3[1,0,0]

4

In [0]:
x3[2,0,0]

8

In [0]:
x3[2,2,2]

0

In [0]:
x3[2,2,2] = 11
x3

array([[[ 5,  0,  3],
        [ 3,  7,  9],
        [ 3,  5,  2]],

       [[ 4,  7,  6],
        [ 8,  8,  1],
        [ 6,  7,  7]],

       [[ 8,  1,  5],
        [ 9,  8,  9],
        [ 4,  3, 11]]])

# **4) Arrays Slicing**

## **a) Slicing Operations on One Dimensional Array**

In [0]:
z1 = np.arange(10)
z1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
z1[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [0]:
z1[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [0]:
z1[4:7]  # middle sub-array

array([4, 5, 6])

In [0]:
z1[::2]  # every other element

array([0, 2, 4, 6, 8])

In [0]:
z1[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [0]:
z1[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [0]:
z1[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## **b) Slicing Operations on Two Dimensional Array**

In [0]:
z2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
z2

array([[3, 5, 0, 2],
       [3, 8, 1, 3],
       [3, 3, 7, 0]])

In [0]:
z2[:2, :3]  # first two rows and first three columns

array([[3, 5, 0],
       [3, 8, 1]])

In [0]:
z2[:3, ::2]  # all rows, every other column

array([[3, 0],
       [3, 1],
       [3, 7]])

In [0]:
print(z2)
z2[::-1, ::-1] # Reverse first rowwise and then columnwise

[[3 5 0 2]
 [3 8 1 3]
 [3 3 7 0]]


array([[0, 7, 3, 3],
       [3, 1, 8, 3],
       [2, 0, 5, 3]])

In [0]:
print(z2[:, 0])  # first column of z2

[3 3 3]


In [0]:
print(z2[0, :])  # first row of x2

[3 5 0 2]


In [0]:
print(z2[0])  # equivalent to x2[0, :]

[3 5 0 2]


## **b) Slicing Operations on Three Dimensional Array**

In [0]:
np.random.seed(0)  # seed for reproducibility
z3 = np.random.randint(10, size=(3, 3, 3))  # Three-dimensional array
z3

array([[[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]],

       [[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]],

       [[8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]]])

In [0]:
z3[0, :2, :2]  # first two rows and first two columns of the first dimension

array([[5, 0],
       [3, 7]])

In [0]:
z3[1, :2, :2]  # first two rows and first two columns of the second dimension

array([[4, 7],
       [8, 8]])

In [0]:
z3[2, :2, :2]  # first two rows and first two columns of the third dimension

array([[8, 1],
       [9, 8]])

# **5) Standard Operations on Arrays**

**Plethora of built-in arithmetic functions are provided in NumPy.**

## **a) Using Basic Arithmetic Operators**

**We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified** 

In [0]:
# Python program to demonstrate 
# basic operations on single array 
import numpy as np 
  
a = np.array([1, 2, 5, 3]) 
  
# add 1 to every element 
print ("Adding 1 to every element:", a+1) 
  
# subtract 3 from each element 
print ("Subtracting 3 from each element:", a-3) 
  
# multiply each element by 10 
print ("Multiplying each element by 10:", a*10) 
  
# square each element 
print ("Squaring each element:", a**2) 
  
# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 
  
# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.T) 

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


## **b) Using Unary operators**

**Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.**

In [0]:
# Python program to demonstrate 
# unary operators in numpy 
import numpy as np 
  
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]]) 
  
# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", 
                    arr.max(axis = 1)) 
  
# minimum element of array 
print ("Column-wise minimum elements:", 
                        arr.min(axis = 0)) 
  
# sum of array elements 
print ("Sum of all array elements:", 
                            arr.sum()) 
  
# cumulative sum along each row 
print ("Cumulative sum along each row:\n", 
                        arr.cumsum(axis = 1)) 

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


## **c) Using Binary operators**

**These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, , etc. In case of +=, -=, = operators, the exsisting array is modified.**

In [0]:
# Python program to demonstrate 
# binary operators in Numpy 
import numpy as np 
  
a = np.array([[1, 2], 
            [3, 4]]) 
b = np.array([[4, 3], 
            [2, 1]]) 
  
# add arrays 
print ("Array sum:\n", a + b) 
  
# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 
  
# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


## **d) Using Universal functions (ufunc)** 

**NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.**

**Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.**

In [0]:
# Python program to demonstrate 
# universal functions in numpy 
import numpy as np 
  
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 
print(a)
print ("Sine values of array elements:", np.sin(a)) 
  
# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 
print(np.exp(1))
  
# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 

[0.         1.57079633 3.14159265]
Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
2.718281828459045
Square root of array elements: [0.         1.         1.41421356 1.73205081]


# **6) Arrays Sorting** 

**There is a simple np.sort method for sorting NumPy arrays. Let’s explore it a bit.**

In [0]:
# Python program to demonstrate sorting in numpy 
import numpy as np 
  
a = np.array([[1, 4, 2], 
                 [3, 4, 6], 
              [0, -1, 5]]) 

print(a)
  
# sorted array 
print ("Array elements in sorted order:\n", 
                    np.sort(a, axis = None)) 
  
# sort array row-wise 
print ("Row-wise sorted array:\n", 
                np.sort(a, axis = 1)) 
  
# specify sort algorithm 
print ("Column wise sort by applying merge-sort:\n", 
            np.sort(a, axis = 0, kind = 'mergesort')) 
  


[[ 1  4  2]
 [ 3  4  6]
 [ 0 -1  5]]
Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


# **7) Reshaping of Arrays**

In [0]:
# Reshaping 3X4 array to 2X2X3 array 
arr = np.array([[1, 2, 3, 4], 
                [5, 2, 4, 2], 
                [1, 2, 0, 1]]) 
print ("\nOriginal array:\n", arr) 
newarr1 = arr.T
newarr1
print("\nTranspose of the array:\n", newarr1)
newarr = arr.reshape(2, 2, 3) 
print ("\nOriginal array:\n", arr) 
print ("Reshaped array:\n", newarr) # Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("Flattened array:\n", flarr) 




Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Transpose of the array:
 [[1 5 1]
 [2 2 2]
 [3 4 0]
 [4 2 1]]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]
